//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userAssign
    {
        public int assignmentID { get; set; }
        public int steps { get; set; }
        public string data { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual adminAssign adminAssign { get; set; }
    }
}
